### ISSUE TITLE
Database memory

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/banana#1]
We experienced a problem with "statefulness" of `yadmark`, since running `FONLL-A` in a bigger run (with plain and scale variations) or in an isolated `yadmark` run produce two different numbers for APFEL, while the APFEL run (and `yadism` as well) should always be isolated, depending only on the inputs.

Since the problem is present with APFEL numbers and not with `yadism` ones it's probably a cache problem introduced by the database.

Here the [`benchmark_against_apfel`](https://github.com/N3PDF/banana/files/5476776/benchmark_against_apfel.zip) runner used for the (quasi-)minimal non-working example, to reproduce the failure (corresponding to N3PDF/yadism@738cbd7fafd290046f9276d44fc900f6efa013a0)

**Comment by AleCandido** [comment]
This should be retested, but I wonder how many things might be breaking in the meanwhile (most likely we were still using `tinydb`, and even the `BenchmarkRunner` had a different interface), so we'll have to write a new runner inspired to the old one.

On one side I believe it's now working, and it'd be worth to test it and make sure (this can be done within #20, for example), but we never had this problem again, so I wonder if it's really worth to keep.

@felixhekhorn, what do you think?

**Comment by felixhekhorn** [comment]
I'd say, we close until we hit it again

**Comment by AleCandido** [comment]
Perfect
