### ISSUE TITLE
Different log layout in yadmark/ekomark

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/banana#12]
Proposal for changing the logs handling. Currently a dirty trick it's temporary implemented:

https://github.com/N3PDF/banana/blob/697c3db91ea13ce9b53ca5fce73f377b3b70d3a1/src/banana/benchmark/runner.py#L305-L310

See https://github.com/N3PDF/eko/pull/65#issuecomment-786036966

**Comment by felixhekhorn** [comment]
solved in https://github.com/N3PDF/eko/pull/65
