### ISSUE TITLE
Generate PDF

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/banana#15]
The project should split in a python API, directly usable by the user to generate & install PDF, and also a CLI, built on top of the API and only facing the easy cases.

## API

- [x] `f(x, Q2)` + flavor mask
  - fixed function for all active flavors and list of active flavors
- [x] support flavor basis, evolution basis, and custom flavor combinations (even not normalized -> evol basis generalization)
- [x] make available function to depend even on PID `f(pid, x, Q2)`, or to be a dictionary `{"pid1": f1, "pid2": f2, ...}` 

## CLI

- [x] select parent PDF
- [x] select either flavor basis or evolution basis elements (flavor specified with PIDs, and evol specified with names like `S`, `g`, `V`, `V24`)

## Bugs
- [x] add a test for Q2 behaviour, as this was a bug in the implementation (now fixed, but not tested)
- [x] there is still a bug in the info dumping (the other day I tried to show to JCM and I failed :upside_down_face: ) - I tried with "NNPDF40 gonly"

**Comment by andreab1997** [comment]
> f(x, Q2) + flavor mask
fixed function for all active flavors and list of active flavors


This can be solved by ` lambda pid, x, Q2: f(x,Q2) if pid in mask else 0. `

**Comment by AleCandido** [comment]
> > f(x, Q2) + flavor mask
> > fixed function for all active flavors and list of active flavors
> 
> This can be solved by `lambda pid, x, Q2: f(x,Q2) if pid in mask else 0.`

True, but if you expose a single function you have to check which object has been passed by the user, if it's a callable with 2 or 3 args (otherwise you could rely on the presence of `mask`, setting it by default to `None` and testing if different).

**Comment by felixhekhorn** [comment]
We're still not convinced of the usefulness of this feature since this can be implemented using the `dict` argument: `{pid: f for pid in mask}` (since in fact we're not allowing the parent set to be a `lambda` as said before ...); and this is only very few characters more then what you want :smiley: )

**Comment by AleCandido** [comment]
Oook

I accept that there is an alternative, and I've no objection to do it in the most practical way, nevertheless if this is the intended way to be used, at least it should be present in an example in the docstring, something like:

```
def blabla(d):
    """
    ...
    
    Examples
    --------
    >>> blabla({pid: f for pid in mask})
    the_output
```

**Comment by AleCandido** [comment]
Can we consider this completed?

**Comment by felixhekhorn** [comment]
I remember, I've send @andreab1997 some comments/improvements of which I don't remember all (actually I don't know where I put them, so I can't look up ...) but the ones I remember I can but here
- [ ] add a test for Q2 behaviour, as this was a bug in the implementation (now fixed, but not tested)
- [ ] there is still a bug in the info dumping (the other day I tried to show to JCM and I failed :upside_down_face: ) - I tried with "NNPDF40 gonly"
- [ ] I seemed to remember there were still some improvements in tests ...

**Comment by andreab1997** [comment]
Yes, I am sorry but, as you remember, I was not able to work on this. Anyway, I believe that there are no serious bugs other the ones you mentioned and that most of the issues are related to tests (which are incomplete at the moment).

**Comment by felixhekhorn** [comment]
calling `genpdf generate -p NNPDF40_nnlo_as_01180  n4uonly 2` we get
 ```
AlphaS_Lambda5: 0.342207, AlphaS_Lambda5: 0.239
AlphaS_MZ: 0.1180024
AlphaS_OrderQCD: 2
[...]
```
which is not readable by LHAPDF

**Comment by andreab1997** [comment]
> 

PR #23 should fix this

**Comment by andreab1997** [comment]
> calling `genpdf generate -p NNPDF40_nnlo_as_01180 n4uonly 2` we get
> 
> ```
> AlphaS_Lambda5: 0.342207, AlphaS_Lambda5: 0.239
> AlphaS_MZ: 0.1180024
> AlphaS_OrderQCD: 2
> [...]
> ```
> 
> which is not readable by LHAPDF

PR #23 should fix this

**Comment by andreab1997** [comment]
In PR #23 there is also the requested Q2 test
