### ISSUE TITLE
DBMS

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/banana#2]
## Requirements
- (optional, but desired) document-oriented, NoSQL
- file-based (embedded)
- thread-safe (transactional)
- python bindings provided

## Choice
For the moment we decided to stick to `sqlite`, because of the following reasons:
- it's one of the [most popular DBMS and for sure the most popular embedded one](https://insights.stackoverflow.com/survey/2020#technology-databases)
- we don't really need the NoSQL layout: everything that is not fitting in a table layout (nested lists/dicts) are never use for querying or db operations, so we can simply keep as they are into [binary blobs](https://www.sqlite.org/faq.html#q10)
- python bindings are in standard library, nothing else it's needed
- it's thread safe
  - **achtung:** there is a writing lock, so only one thread at a time will be able to dump the logs, but this is not a problem: usually write time is ~0.1s or less, for a full transaction, so we'll have a low write occupancy ($time_writing/(last_write - first_write)$), and we just need to write asynchronously acquiring the lock (and so it'll wait otherwise), should be perfectly possible in pure python

**Comment by felixhekhorn** [comment]
- will maybe fix #1 

options:
- sqlite
- https://symas.com/lmdb/technical/

**Comment by felixhekhorn** [comment]
`sqlite3` it is
