### ISSUE TITLE
Where is `genpdf`?

### ISSUE THREAD

**Issue by scarlehoff** [N3PDF/banana#25]
In the toml file in main there's the `genpdf` script https://github.com/N3PDF/banana/blob/4f05d441a7e21d718cffb4c0dc47b49feeb28887/pyproject.toml#L63 and references to a folder `src/banana/tools/genpdf/` but I cannot find it in the repository.

Maybe a merge operation didn't go well?

**Comment by scarlehoff** [comment]
@AleCandido I just realised this was blocking `conda-forge` (I could swear I left it last week with a green tick but apparently not)

**Comment by AleCandido** [comment]
That's just a leftover, `genpdf` is now part of `ekobox`

**Comment by scarlehoff** [comment]
I see. Could you remove it and make a new release so I can reping the conda-forge guy?

**Comment by AleCandido** [comment]
For `banana` the new release is already available. I also introduced in `eko`, but imho there a release is not urgent.

**Comment by scarlehoff** [comment]
Great, thanks!
