### ISSUE TITLE
Generate OCards in the runners

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/banana#3]
### Problem
Generating observables/operators cards it's not the same thing of generating theory cards:
- we know all the theory combinations that may happen (even external-program-wise, e.g. APFEL or QCDNUM), and we can enumerate them in a database and query over
- instead we don't know all the observables, they are infinite, not only *in theory* (as quark masses), but also *in practice*, e.g. because we could slice a lot of different ranges in the 2d plan (x,Q2), or (Q0,Q2) for operators
- in particular ocards are also not completely independent of everything: they strongly depend on theory, e.g. `PTO`, but also `FNS`, and so on

### Proposal
Write the OCards generation directly in the runners. This is the dual part of the exceptions that are currently used, but they are much more natural.

With exceptions:
1. we make the effort of generate observable per external-program/theory-subset
2. then we slice out something in the runner, to fine tune it

With runners generation:
1. a single operation is needed, generation, and it is close to what is actually done in `sandbox`, so once tested with `sandbox` we'll be able to transfer as a regular benchmark

### Layouts
There are two possible layouts.

#### Classes
Since `pytest` it's aware of classes, we are already using them.

```python
import yadmark.data.ocards_tools as otools

class ApfelBenchmark:
   @statichmethod
   def ocards():
       ... # use otools

class BenchmarkSomething(ApfelBenchmark):
   @statichmethod
   def ocards():
       super().ocards()
       ...
```

What we can do it's generate one or multiple OCards per class, simply providing a method for each class called `ocards()` for example.

Then:
- the parent class of each runner should define a template for `ocards()` (maybe an early version may be defined by ekomark/yadmark themselves)
- the actual classes can make use of this one (or whatever it was called) to extend it for the specific case
- when the CLI is called on a specific runner, it will:
  - load the runner as a module
  - parse all the classes matching the `pytest` pattern (e.g. `Benchmark.*`)
  - call all the methods `ocards` of those classes (static or class methods) to obtain the specs for the respective OCards
  - use the specs to generate the OCards (with a pointer telling the class they referred to, or stored in a suitable place/way such that they keep the relation with the generating class)

#### Decorator
Since we are going to unpack a lot, there will be almost a class per benchmark, or maybe a class it will just collect different perturbative orders. Then maybe we can immediately drop classes and work already on single functions.

```python
import yadmark.data.ocards_tools as otools

def make_ocards(ocard_specs):
    ... # use ocard_specs to make ocard_generate
    return ocard_generator

def load_ocards(ocard_specs):
    ... 
    def add_load_skill(benchmark_specs):
        ... # add to benchmark_specs a pointer to related ocards, or the skill to load them
    ...
    return add_load_skill

@make_ocards
def ocards_xxx():
    ...

@load_ocards(ocards_xxx)
def benchmark_xxx():
    ...
```
The steps needed from the user are the same as in the [previous layout](#Classes).

In particular `make_ocards()` provide all the common boilerplate for the ocard generations, augmenting the definition of the single generators, such that they have to define the observables/operators only declaratively.

On the other hand the `load_ocards()` will simply be a pointer, to use the ocards generated by the individual ocard generating function in the respective individual benchmark.

### What should fit in Banana?
Runners are not a part of `banana`, but all the tools that are used all over the place (for example generation CLI) should fit here.

In particular:
1. the user of `banana` should use the OCard generation API from `banana` to define the abstract base class of the runner, from which all the actual `BenchmarkSomething` used by `pytest` inherit.
  - possibly this API can be extended by things specific to eko/yadism in ekomark/yadmark, and then the runner should use the local one
2. run the `generate_ocards <runner>` CLI, that will parse the runner to generate the ocards
3. run `pytest <runner>` to finally run the benchmarks

**Comment by felixhekhorn** [comment]
Solved by classes
