### ISSUE TITLE
True DB Interface

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/banana#7]
Create a real database interface, to represent our data model and manage database operations ([ORM](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping)).

- [x] initialize db
  - a single database will be used per program: `benchmarks.sqlite`
  - make initialization a script (maybe with an entrypoint)
- [x] implement the objects: `Theory`, `OCard`, `Cache`, `Log` (the last it's just a layer around `Dfd`)
- [x] ~for each object implement dump method~ (implemented ORM)
  - make a `staticmethod`, such that we'll operate generically on list of objects (if more than a single one is provided we attempt to write them all in a single transaction)
- [ ] implement the `hash` + `tags` logic

A very good ORM library it's [Django's](https://docs.djangoproject.com/en/3.1/topics/db/), but Django it's a huge web framework, and even if [people say it's quite decoupled](https://stackoverflow.com/a/54046/8653979) I would suggest the same to use something else, like the popular [SQLAlchemy](https://www.sqlalchemy.org/), or implement from scratch on our own.

**Comment by felixhekhorn** [comment]
- **drop pickle**
- [ ] make `loads/dumps` for our objects
- [ ] make schema for our db **OR** adapt constructors
- [ ] provide defaults with proper types

**Comment by AleCandido** [comment]
This is old enough that we realized:

- we don't need `tags` any longer
- since we only pickle our own objects, and read from there, security issues are not the main concern

Still, it might be nice to drop `pickle`, but I'd say is not a priority, nor it belongs to this issue any longer.

I'm proposing to close.

**Comment by felixhekhorn** [comment]
Agreed - tags is basically replaced by methods; should we open a new issue for pickle (which at this point is a nice-to-have)?

**Comment by AleCandido** [comment]
If you wish, yes, we can keep `pickle` as a low priority (but scheduled) feature.
