### ISSUE TITLE
Adapt navigator

### ISSUE THREAD

**Issue by AleCandido** [N3PDF/banana#8]
Since we are changing database layout, we need to properly adequate the navigator too.

- [x] adapt to the new database
- [ ] allow for cross-external comparison
  - e.g.: APFEL vs QCDNUM

**Comment by felixhekhorn** [comment]
> allow for cross-external comparison 

@AleCandido this should already work, right?

**Comment by AleCandido** [comment]
Try, if you can produce it that's fine :)
